<?php

namespace Bronowicki\SampleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShopUserModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopUserModelRepository extends EntityRepository
{
}
